sudo: required
language: generic
Services:
  - docker
before_install:
  - docker build -t mageshmsc83/t4 -f dockerfile.dev .
script:
  - docker run -e cI=true mageshmsc83/t4 npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mydocker"
  env: "M"ydocker-env"
  bucket-name: "elasticbeanstalk-us-east-2-306439872146"
  bucket-path: "mydocker"
  on:
    branch: master
access_key_id: $AWS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY