sudo: required
Services:
  - docker
before_install:
  - docker build -t mageshmsc83/t3 .
script:
  - docker run mageshmsc83/t3
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: mydocker
  env: Mydocker-env
  bucket-name: elasticbeanstalk-us-east-2-306439872146
  bucket-path: mydocker
  on:
    branch: master
access_key_id: $AWS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY