sudo: required
language: generic
Services:
  - docker
before_install:
  - docker build -t mageshmsc83/t4 -f Dockerfile.dev .
script:
  - docker run -e CI=true mageshmsc83/t4 npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'mydocker1'
  env: 'mydocker1-env'
  bucket-name: 'elasticbeanstalk-us-east-2-306439872146'
  bucket-path: 'mydocker'
  on:
    branch: master
  access_key_id: 'AKIAUOWJ5L2JBOY4U2UW'
  secret_access_key: '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'